Run calculate_bleu_on_subset only on master
Summary:
I was getting the following error for some runs

```
RuntimeError: unique: failed to synchronize: an illegal memory access was encountered
```
and asked it here. https://fb.facebook.com/groups/1405155842844877/permalink/2493007600726357/

Turns out we are calling this function from all processes and it's causing memory corruption.
We should either make this function thread safe or don't call it from all processes.

We call save_and_eval only from master, we should do the same thing for this one for now.

Reviewed By: theweiho

Differential Revision: D13217438

fbshipit-source-id: 4456b5366247f82902948689ec70314f10415dd4